name: Riderekta
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter


  fl_chart: ^0.68.0
  animate_do: ^3.3.4
  file_picker: ^8.0.0
  shared_preferences: ^2.2.3
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ebike1.jpg
    - assets/ebike2.jpg
    - assets/ebike3.jpg
    - assets/Riderekta.png
    - assets/images/yesha.png
    - assets/images/geraldine.png
    - assets/images/kyla.png
    - assets/images/noel.png

# ğŸ‘‡ moved this block OUT of flutter: (root level)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Riderekta.png"
  adaptive_icon_background: "#ffffff"      # solid color OR image path
  adaptive_icon_foreground: "assets/Riderekta.png"